config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # API
  namespace :api do
    namespace :v2 do
      resources :candidates, only: [:index, :show]
    end
  end

  resources :candidates do
    member do
      put :vote
      get :log
    end
  end

  root 'candidates#index'

  # /api/v2/candidates
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  paginates_per 10
  has_many :vote_logs
  has_many :users, through: :vote_logs

  validates :name, presence: true
  validates :age, numericality: { greater_than_or_equal_to: 40 }

  default_scope { where(deleted_at: nil) }

  def destroy
    update(deleted_at: Time.now)
  end
end

app/models/cart.rb
class Cart
attr_reader :items

    def initialize
      @items = []
    end
  
  
    def empty?
      @items.empty?
    end
  
    def add_item(product_id)
    found_item = @items.find {|i| i.product_id == product_id}
      if found_item
        found_item.increment(1)
      else
        @items << CartItem.new(product_id)
      end
    end

    def total_price
        total = items.reduce(0){|sum, item| sum + item.price }
        total = total *0.9 if super_good_day?
        total
    end



    private

    def super_good_day?
        Time.now.day == 10 && Time.now.month == 2
    end
  
end

app/models/cart_item.rb
class CartItem
    attr_reader :product_id, :quantity

    def initialize(product_id, quantity = 1)
        @product_id = product_id
        @quantity = quantity
    end

    def increment(n = 1)
        @quantity += n
    end


    def product 
        Product.find_by(id: product_id)
    end

    def price
        product.price * quantity
    end


end

app/models/product.rb
class Product < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :vote_logs
  has_many :candidates, through: :vote_logs
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate, counter_cache: true
  belongs_to :user

  validate :validate_vote

  private
  def validate_vote
    if VoteLog.exists?(candidate: candidate, user: user)
      errors[:候選人] << "已經投過了!"
    elsif user.vote_logs.count >= 3
      errors[:投票] << "不能超過 3 筆!"
    end
  end
end

app/controllers/api/v2/candidates_controller.rb
class Api::V2::CandidatesController < ApplicationController
  def index
    @candidates = Candidate.all
  end

  def show
    @candidate = Candidate.find_by(id: params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :find_candidate, only: [:show, :edit, :update, :destroy, :vote, :log]

  def index
    @candidates = Candidate.order(vote: :desc).page(params[:page])
  end

  def show
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)

    if @candidate.save
      redirect_to root_path, notice: "新增候選人成功!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @candidate.update(candidate_params)
      redirect_to root_path, notice: "更新成功"
    else
      render :edit
    end
  end

  def destroy
    @candidate.destroy
    redirect_to root_path, notice: "資料刪除成功!"
  end

  def vote
    if user_signed_in?

      log = current_user.vote_logs.new(candidate: @candidate,
                                       ip_address: request.remote_ip)

      if log.save
        message = "投票成功"
      else
        message = log.errors.full_messages.first
      end

      redirect_to root_path, notice: message
    else
      redirect_to root_path, notice: '請先登入會員!'
    end
  end

  def log
    @logs = @candidate.vote_logs.includes(:user)
  end

  private
  def find_candidate
    @candidate = Candidate.find_by(id: params[:id])
  end

  # Strong Parameters
  def candidate_params
    params.require(:candidate).permit(:name, :age, :policy, :party, :degree)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/_form.html.erb
<%= simple_form_for(candidate) do |form| %>
  <div class="box">
    <%= form.input :name, label: '姓名' %>
    <%= form.input :degree, label: '學歷' %>
    <%= form.input :party, label: '政黨' %>
    <%= form.input :age, label: '年紀' %>
    <%= form.input :policy, label: '政見' %>
    <%= form.submit class: 'btn btn-success btn-lg' %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>編輯候選人</h1>

<%= render 'form', candidate: @candidate %>

app/views/candidates/index.html.erb
<h1>候選人列表</h1>

<%= paginate @candidates, theme: 'twitter-bootstrap-4' %>

<table class="table table-hover table-sm">
  <thead>
    <tr>
      <th>投票</th>
      <th>得票數</th>
      <th>候選人</th>
      <th>處理</th>
    </tr>
  </thead>
  <tbody>
    <% @candidates.each do |candidate| %>
    <tr>
      <td>
        <%= link_to "投票！", vote_candidate_path(candidate), class: 'btn btn-sm btn-warning', method: 'put', data: { confirm: '確認投票?!'} %>
      </td>
      <td>
        <%= link_to "#{candidate.vote_logs_count} 票", log_candidate_path(candidate) %>
      </td>
      <td>
          <%= link_to candidate.name, candidate_path(candidate) %>
      </td>
      <td>
        <%= link_to "編輯", edit_candidate_path(candidate), class: 'btn btn-sm btn-success' %>
        <%= link_to "刪除", candidate_path(candidate), class: 'btn btn-sm btn-danger', method: 'delete', data: { confirm: '確定嗎?!'} %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '新增候選人', new_candidate_path, class: 'btn btn-primary btn-lg' %>

app/views/candidates/log.html.erb
<h1>投票紀錄</h1>

<ul>
<% @logs.each do |log| %>
  <li><%= log.user.email %></li>
<% end %>
</ul>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<%= render 'form', candidate: @candidate %>

app/views/candidates/show.html.erb
<% if @candidate  %>
  <h1><%= @candidate.name %></h1>

  <ul>
    <li>得票數：<%= @candidate.vote %>票</li>
    <li>年紀：<%= @candidate.age %></li>
    <li>學歷：<%= @candidate.degree %></li>
    <li>黨派：<%= @candidate.party %></li>
    <li>政見：<%= @candidate.policy %></li>
  </ul>
<% else %>
  <h1>沒有這個人</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ivoting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/frontend/navbar' %>
    <%= render 'shared/frontend/flash' if notice %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/frontend/_flash.html.erb
<div class="alert alert-success" role="alert">
  <%= notice %>
</div>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "iVoting", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "候選人列表", candidates_path, class: 'nav-link' %>
      </li>
    </ul>

    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "登出", destroy_user_session_path, class: 'nav-link', method: 'delete' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "註冊", new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "登入", new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>


  </div>
</nav>